In [1]:
import numpy as np
from scipy.stats import wilcoxon
import pandas as pd

In [2]:
f3_1 =  [0.4921906590461731, 0.5215432643890381, 0.5229765176773071, 0.5906912088394165, 0.5974832773208618, 0.5967130661010742, 0.49372604489326477, 0.5016021132469177, 0.5831577777862549, 0.50162672996521]
f3_10 = [0.6114784479141235, 0.6271606087684631, 0.650913417339325, 0.7124035358428955, 0.6562206149101257, 0.5781388282775879, 0.6108881235122681, 0.6606954336166382, 0.7146749496459961, 0.5925798416137695]
f3_50 = [0.7391114830970764, 0.7138891816139221, 0.7079664468765259, 0.6853654384613037, 0.7142417430877686, 0.7120077610015869, 0.7076694965362549, 0.6953688263893127, 0.7081575393676758, 0.7173869013786316]
f3_100 = [0.6854907274246216, 0.7018877267837524, 0.7051329612731934, 0.7071099281311035, 0.7234624624252319, 0.6829464435577393, 0.6809353828430176, 0.7206363677978516, 0.710473895072937, 0.7149356603622437]

In [3]:
seam_ai_1 = [0.377860963344574, 0.4130123257637024, 0.47297513484954834, 0.45575129985809326, 0.4257469177246094, 0.48470115661621094, 0.3885546922683716, 0.4267796576023102, 0.46391648054122925, 0.4748969078063965]
seam_ai_10 = [0.5586085319519043, 0.6349080204963684, 0.7045071125030518, 0.6360519528388977, 0.6678024530410767, 0.5737863779067993, 0.6507954597473145, 0.6220990419387817, 0.6938204765319824, 0.6484290361404419]
seam_ai_50 = [0.7323266267776489, 0.7172337174415588, 0.6943792104721069, 0.7482177019119263, 0.694536566734314, 0.7153350710868835, 0.7017015218734741, 0.6794829368591309, 0.6997905969619751, 0.7117389440536499]
seam_ai_100 = [0.7056831121444702, 0.7334968447685242, 0.7136412858963013, 0.6950341463088989, 0.7004083395004272, 0.7282794713973999, 0.7273871302604675, 0.6763520240783691, 0.730455756187439, 0.7129467725753784]

In [4]:
both_1 = [0.37591788172721863, 0.44865068793296814, 0.3879006505012512, 0.45429059863090515, 0.6344413757324219, 0.5228689908981323, 0.4406561851501465, 0.4452006220817566, 0.5890308618545532, 0.44818979501724243]
both_10 = [0.6278742551803589, 0.6060476303100586, 0.6036739349365234, 0.5823737382888794, 0.638785719871521, 0.7036415338516235, 0.656001091003418, 0.6887655258178711, 0.5779730081558228, 0.6024499535560608]
both_50 = [0.6860657930374146, 0.684974193572998, 0.691747784614563, 0.675595760345459, 0.6730674505233765, 0.656542181968689, 0.6630933284759521, 0.7056043148040771, 0.6740154027938843, 0.7051478624343872]
both_100 = [0.7205779552459717, 0.7280673980712891, 0.6954821348190308, 0.6602529287338257, 0.6886835098266602, 0.7284505367279053, 0.6866927146911621, 0.6994243264198303, 0.7187545299530029, 0.6913012266159058]

In [5]:
coco_1 = [0.3769932985305786, 0.3498465418815613, 0.3968495726585388, 0.430780827999115, 0.45610350370407104, 0.46036970615386963, 0.41675323247909546, 0.34573638439178467, 0.40180981159210205, 0.4258032441139221]
coco_10 = [0.6435966491699219, 0.6850297451019287, 0.6049833297729492, 0.5892685651779175, 0.6367080211639404, 0.6513617634773254, 0.5847228765487671, 0.6998995542526245, 0.6134811639785767, 0.6134132146835327]
coco_50 = [0.7140721082687378, 0.6916694641113281, 0.720165491104126, 0.7231333255767822, 0.6827823519706726, 0.6785625219345093, 0.6687397956848145, 0.7140922546386719, 0.713681161403656, 0.6873306632041931]
coco_100 = [0.6844767332077026, 0.728105366230011, 0.6866030693054199, 0.6944726705551147, 0.7135407328605652, 0.6933058500289917, 0.7111217975616455, 0.697007417678833, 0.7155164480209351, 0.7096837162971497]

In [6]:
imagenet_1 = [0.3867160677909851, 0.3333248794078827, 0.30170607566833496, 0.4317062497138977, 0.44541144371032715, 0.4637402892112732, 0.3474276661872864, 0.31782883405685425, 0.4005688428878784, 0.34538111090660095]
imagenet_10 = [0.6288987398147583, 0.6834924221038818, 0.5924158692359924, 0.5859583616256714, 0.6593750715255737, 0.5813468098640442, 0.5960836410522461, 0.5976132154464722, 0.5780667662620544, 0.6152050495147705]
imagenet_50 = [0.703382134437561, 0.7002999782562256, 0.711971640586853, 0.6853923797607422, 0.6924941539764404, 0.6839581727981567, 0.6979377269744873, 0.6901819109916687, 0.7335787415504456, 0.6623022556304932]
imagenet_100 = [0.6946904063224792, 0.6924375295639038, 0.6768949627876282, 0.7092676758766174, 0.7018483877182007, 0.714194655418396, 0.7232003211975098, 0.6948549151420593, 0.6638655662536621, 0.6939460039138794]

In [7]:
sup_1 = [0.3545294404029846, 0.35205668210983276, 0.34178274869918823, 0.38085436820983887, 0.3441429138183594, 0.41109365224838257, 0.3601357340812683, 0.40360426902770996, 0.37348565459251404, 0.41470637917518616]
sup_10 = [0.5857870578765869, 0.6980957388877869, 0.6338291764259338, 0.6696898341178894, 0.6179171204566956, 0.6615892648696899, 0.6159988045692444, 0.5930278301239014, 0.6340755820274353, 0.6286380887031555]
sup_50 = [0.6840147972106934, 0.7100231647491455, 0.6505007743835449, 0.7061741948127747, 0.7114495635032654, 0.7157145738601685, 0.7120320200920105, 0.6977530121803284, 0.6934067606925964, 0.6991138458251953]
sup_100 = [0.6982303857803345, 0.680687665939331, 0.725877046585083, 0.7232306599617004, 0.7121431827545166, 0.7040040493011475, 0.7129974365234375, 0.7094368934631348, 0.7157259583473206, 0.7145935297012329]

In [8]:
# dados_1 = {'f3': f3_1, 'seam_ai':seam_ai_1, 'both':both_1, 'coco':coco_1, 'imagenet':imagenet_1, 'sup':sup_1}
dados_1 = [f3_1, seam_ai_1, both_1, coco_1, imagenet_1, sup_1]
dados_10 = [f3_10, seam_ai_10, both_10, coco_10, imagenet_10, sup_10]
nomes = ['f3', 'seam_ai', 'both', 'coco', 'imagenet', 'sup']

In [9]:
teste_1 = []

for i in range(len(dados_1)):
    for j in range(i+1, len(dados_1)):
        aux = [nomes[i], nomes[j], wilcoxon(dados_1[i], dados_1[j]).pvalue]
        teste_1.append(aux)
        # print(f'{nomes_1[i]} + {nomes_1[j]} -> p: {wilcoxon(dados_1[i], dados_1[j]).pvalue:.5f}')
        
# print()
        

teste_1.sort(key=lambda x: x[2], reverse=True)
for i in teste_1:
    print(f'{i[0]} + {i[1]} -> p: {i[2]:.5f}')

imagenet + sup -> p: 0.84570
seam_ai + both -> p: 0.23242
coco + sup -> p: 0.08398
seam_ai + coco -> p: 0.06445
coco + imagenet -> p: 0.04883
f3 + both -> p: 0.00977
seam_ai + imagenet -> p: 0.00977
both + coco -> p: 0.00977
both + imagenet -> p: 0.00391
f3 + seam_ai -> p: 0.00195
f3 + coco -> p: 0.00195
f3 + imagenet -> p: 0.00195
f3 + sup -> p: 0.00195
seam_ai + sup -> p: 0.00195
both + sup -> p: 0.00195

In [10]:
teste_10 = []

for i in range(len(dados_1)):
    for j in range(i+1, len(dados_1)):
        aux = [nomes[i], nomes[j], wilcoxon(dados_10[i], dados_10[j]).pvalue]
        teste_10.append(aux)
        # print(f'{nomes_1[i]} + {nomes_1[j]} -> p: {wilcoxon(dados_1[i], dados_1[j]).pvalue:.5f}')
        
# print()
        

teste_10.sort(key=lambda x: x[2], reverse=True)
for i in teste_10:
    print(f'{i[0]} + {i[1]} -> p: {i[2]:.5f}')

f3 + seam_ai -> p: 1.00000
f3 + coco -> p: 0.92188
seam_ai + coco -> p: 0.92188
both + sup -> p: 0.92188
both + imagenet -> p: 0.84570
seam_ai + both -> p: 0.76953
seam_ai + sup -> p: 0.76953
f3 + sup -> p: 0.69531
f3 + both -> p: 0.62500
coco + sup -> p: 0.62500
both + coco -> p: 0.43164
f3 + imagenet -> p: 0.37500
seam_ai + imagenet -> p: 0.19336
imagenet + sup -> p: 0.19336
coco + imagenet -> p: 0.16016

In [11]:

df_teste_10 = pd.DataFrame(teste_10, columns=['Variable 1', 'Variable 2', 'p-value'])
df_teste_1 = pd.DataFrame(teste_1, columns=['Variable 1', 'Variable 2', 'p-value'])

In [12]:
df_teste_1

   Variable 1 Variable 2   p-value
0    imagenet        sup  0.845703
1     seam_ai       both  0.232422
2        coco        sup  0.083984
3     seam_ai       coco  0.064453
4        coco   imagenet  0.048828
5          f3       both  0.009766
6     seam_ai   imagenet  0.009766
7        both       coco  0.009766
8        both   imagenet  0.003906
9          f3    seam_ai  0.001953
10         f3       coco  0.001953
11         f3   imagenet  0.001953
12         f3        sup  0.001953
13    seam_ai        sup  0.001953
14       both        sup  0.001953

In [13]:
f3_1 = [0.4837018847465515, 0.5869656801223755, 0.5734267830848694, 0.5141896605491638, 0.5960383415222168, 0.5243850946426392, 0.4908736050128937, 0.5471756458282471, 0.6522148847579956, 0.4844317138195038]
f3_10 = [0.6767640113830566, 0.6822337508201599, 0.6396908760070801, 0.706199586391449, 0.6589066982269287, 0.7076795101165771, 0.7047411203384399, 0.6804614067077637, 0.7125924825668335, 0.6860674619674683]
f3_50 = [0.7413786053657532, 0.7533098459243774, 0.7235890626907349, 0.7199782133102417, 0.7685572504997253, 0.7280473113059998, 0.7477256655693054, 0.7429788112640381, 0.717410147190094, 0.7229605317115784]
f3_100 = [0.7169620990753174, 0.7442376017570496, 0.7219040989875793, 0.7114347219467163, 0.7220809459686279, 0.7194674015045166, 0.7162190079689026, 0.6962233781814575, 0.7029454112052917, 0.7369436025619507]

In [14]:
seam_ai_1 = [0.5745084285736084, 0.6621048450469971, 0.582252562046051, 0.5340155959129333, 0.6205821633338928, 0.5723899006843567, 0.6007736921310425, 0.5974997282028198, 0.6326844692230225, 0.5347815752029419]
seam_ai_10 = [0.6812978386878967, 0.7123841643333435, 0.7462108135223389, 0.7395094633102417, 0.7096425294876099, 0.7060501575469971, 0.6835981607437134, 0.6649969816207886, 0.7279021739959717, 0.6757397651672363]
seam_ai_50 = [0.7466174364089966, 0.7307068109512329, 0.7366724610328674, 0.7255212664604187, 0.7164716720581055, 0.709700345993042, 0.7351818084716797, 0.7514280080795288, 0.7258813381195068, 0.7223782539367676]
seam_ai_100 = [0.7259001135826111, 0.6947828531265259, 0.7369838953018188, 0.7404259443283081, 0.7007603645324707, 0.7139555215835571, 0.7211179733276367, 0.7630149722099304, 0.7388298511505127, 0.7239240407943726]

In [15]:
both_1 = [0.5544216632843018, 0.5828972458839417, 0.5573316812515259, 0.5182050466537476, 0.6458766460418701, 0.5511695742607117, 0.5375746488571167, 0.4780445098876953, 0.641359806060791, 0.44797736406326294]
both_10 = [0.7002550363540649, 0.7755658626556396, 0.7029491662979126, 0.6946004629135132, 0.6716361045837402, 0.7062398791313171, 0.7252161502838135, 0.6806384325027466, 0.7340912222862244, 0.6911832690238953]
both_50 = [0.747839093208313, 0.7377122640609741, 0.7295509576797485, 0.7311639189720154, 0.7134615182876587, 0.7424837350845337, 0.7104682922363281, 0.710601806640625, 0.7017228007316589, 0.7323529720306396]
both_100 = [0.7476893067359924, 0.7388412356376648, 0.7233585119247437, 0.7305166721343994, 0.7271303534507751, 0.7073785066604614, 0.7235655784606934, 0.7193956971168518, 0.7214333415031433, 0.7430347204208374]

In [16]:
coco_1 = [0.552832841873169, 0.6437995433807373, 0.5746729373931885, 0.5331947803497314, 0.6615182161331177, 0.576276957988739, 0.6010376214981079, 0.5439026355743408, 0.6862090826034546, 0.6133313179016113]
coco_10 = [0.6872207522392273, 0.6938159465789795, 0.6586702466011047, 0.7074401378631592, 0.7157458662986755, 0.7078001499176025, 0.7130877375602722, 0.7202891111373901, 0.6946384906768799, 0.7236686944961548]
coco_50 = [0.7399826049804688, 0.7303330898284912, 0.7336924076080322, 0.7350263595581055, 0.7196556329727173, 0.7411222457885742, 0.7138381004333496, 0.731724739074707, 0.7041137218475342, 0.722259521484375]
coco_100 = [0.715880274772644, 0.7372825145721436, 0.7012811899185181, 0.7364312410354614, 0.7483310699462891, 0.7678948640823364, 0.7045480608940125, 0.7351146936416626, 0.7507054209709167, 0.7286060452461243]

In [17]:
imagenet_1 = [0.565768837928772, 0.6801146268844604, 0.5834623575210571, 0.5300043821334839, 0.5681078433990479, 0.5392690896987915, 0.5372714400291443, 0.5335404872894287, 0.6491206884384155, 0.5063568353652954]
imagenet_10 = [0.7235898971557617, 0.7429518103599548, 0.6146338582038879, 0.6590032577514648, 0.685692548751831, 0.6899377107620239, 0.696865439414978, 0.7427975535392761, 0.7013902068138123, 0.6542002558708191]
imagenet_50 = [0.7012426853179932, 0.7353851199150085, 0.7122901082038879, 0.7264569997787476, 0.7162564992904663, 0.7528119683265686, 0.7264949083328247, 0.7230662107467651, 0.7587159276008606, 0.7213091254234314]
imagenet_100 = [0.7378535270690918, 0.7004860639572144, 0.7501661777496338, 0.7557029724121094, 0.7376048564910889, 0.7312161326408386, 0.7132982611656189, 0.7065786123275757, 0.7529860138893127, 0.7386754155158997]

In [18]:
sup_1 = [0.5355184078216553, 0.6192345023155212, 0.517974317073822, 0.5614939332008362, 0.5892818570137024, 0.5608556270599365, 0.5453529357910156, 0.535880982875824, 0.6133626699447632, 0.5436421632766724]
sup_10 = [0.683888852596283, 0.7278646230697632, 0.6838400363922119, 0.7073788642883301, 0.6718495488166809, 0.6959601044654846, 0.6827496290206909, 0.712338387966156, 0.6485361456871033, 0.7262653112411499]
sup_50 = [0.7439100742340088, 0.7468907833099365, 0.7179890871047974, 0.7247728705406189, 0.7443149089813232, 0.7376962304115295, 0.7549659609794617, 0.717842161655426, 0.723484992980957, 0.7523925304412842]
sup_100 = [0.7352644205093384, 0.735403299331665, 0.7302104830741882, 0.7147461175918579, 0.7185119390487671, 0.715186595916748, 0.7565402984619141, 0.7344087362289429, 0.7365639805793762, 0.7247927784919739]

In [19]:
dados_1 = [f3_1, seam_ai_1, both_1, coco_1, imagenet_1, sup_1]
dados_10 = [f3_10, seam_ai_10, both_10, coco_10, imagenet_10, sup_10]
nomes = ['f3', 'seam_ai', 'both', 'coco', 'imagenet', 'sup']

In [20]:
teste_1 = []

for i in range(len(dados_1)):
    for j in range(i+1, len(dados_1)):
        aux = [nomes[i], nomes[j], wilcoxon(dados_1[i], dados_1[j]).pvalue]
        teste_1.append(aux)
        # print(f'{nomes_1[i]} + {nomes_1[j]} -> p: {wilcoxon(dados_1[i], dados_1[j]).pvalue:.5f}')
        
# print()
        

teste_1.sort(key=lambda x: x[2], reverse=True)
for i in teste_1:
    print(f'{i[0]} + {i[1]} -> p: {i[2]:.5f}')

seam_ai + coco -> p: 0.92188
f3 + both -> p: 0.76953
imagenet + sup -> p: 0.76953
both + sup -> p: 0.55664
f3 + sup -> p: 0.32227
both + imagenet -> p: 0.23242
f3 + imagenet -> p: 0.10547
coco + imagenet -> p: 0.10547
seam_ai + imagenet -> p: 0.08398
seam_ai + both -> p: 0.03711
seam_ai + sup -> p: 0.01953
coco + sup -> p: 0.01953
f3 + seam_ai -> p: 0.00586
f3 + coco -> p: 0.00586
both + coco -> p: 0.00391

In [21]:
df_teste_1 = pd.DataFrame(teste_1, columns=['Variable 1', 'Variable 2', 'p-value'])
df_teste_1

   Variable 1 Variable 2   p-value
0     seam_ai       coco  0.921875
1          f3       both  0.769531
2    imagenet        sup  0.769531
3        both        sup  0.556641
4          f3        sup  0.322266
5        both   imagenet  0.232422
6          f3   imagenet  0.105469
7        coco   imagenet  0.105469
8     seam_ai   imagenet  0.083984
9     seam_ai       both  0.037109
10    seam_ai        sup  0.019531
11       coco        sup  0.019531
12         f3    seam_ai  0.005859
13         f3       coco  0.005859
14       both       coco  0.003906

In [22]:
teste_01 = []

for i in range(len(dados_1)):
    for j in range(i+1, len(dados_1)):
        aux = [nomes[i], nomes[j], wilcoxon(dados_1[i], dados_1[j]).pvalue]
        teste_01.append(aux)

In [23]:
df_teste_01 = pd.DataFrame(teste_01, columns=['Variable 1', 'Variable 2', 'p-value'])
df_teste_01

   Variable 1 Variable 2   p-value
0          f3    seam_ai  0.005859
1          f3       both  0.769531
2          f3       coco  0.005859
3          f3   imagenet  0.105469
4          f3        sup  0.322266
5     seam_ai       both  0.037109
6     seam_ai       coco  0.921875
7     seam_ai   imagenet  0.083984
8     seam_ai        sup  0.019531
9        both       coco  0.003906
10       both   imagenet  0.232422
11       both        sup  0.556641
12       coco   imagenet  0.105469
13       coco        sup  0.019531
14   imagenet        sup  0.769531